# ClashMeta 官方文档：https://wiki.metacubex.one/
# ClashMeta 核心下载地址：https://github.com/MetaCubeX/ClashMetaForAndroid/releases

# 代理提供(订阅)组，添加/修改机场名请保证 proxy-providers 名称和 proxy-groups 同步添加/修改
proxy-providers:
  订阅1:
    type: http
    path: ./ProxyProviders/订阅1.yaml
    url: ""
    interval: 86400
    health-check: {enable: true, url: https://www.gstatic.com/generate_204, interval: 86400, timeout: 5000}
    override: {skip-cert-verify: true, dialer-proxy: "百度直连", additional-suffix: " -CC"}

  订阅2:
    type: http
    path: ./ProxyProviders/订阅2.yaml
    url: "https://hjdy.ukuk358.xyz/uukk"
    interval: 86400
    health-check: {enable: true, url: https://www.gstatic.com/generate_204, interval: 86400, timeout: 5000}
    override: {skip-cert-verify: true, dialer-proxy: "百度直连", additional-suffix: ""}

  订阅3:
    type: http
    path: ./ProxyProviders/订阅3.yaml
    url: "https://url.wgys.eu.org/3vs1"
    interval: 86400
    health-check: {enable: true, url: https://www.gstatic.com/generate_204, interval: 86400, timeout: 5000}
    override: {skip-cert-verify: true, dialer-proxy: "百度直连", additional-suffix: " -3v1"}

  订阅4:
    type: http
    path: ./ProxyProviders/订阅4.yaml
    url: ""
    interval: 86400
    health-check: {enable: true, url: https://www.gstatic.com/generate_204, interval: 86400, timeout: 5000}
    override: {skip-cert-verify: true, dialer-proxy: "百度直连", additional-suffix: " | OTC"}

  # YAML/uri/base64 不可写在同一文件，uri/base64 不需要 proxies: 字段，直接书写即可
  # YAML格式： {- name: "vmess", type: ss, server: server, port: 443, ······}
  本地节点(YAML):
    type: file
    path: ./ProxyProviders/本地节点(YAML).yaml
    health-check: {enable: true, url: https://www.gstatic.com/generate_204, interval: 86400, timeout: 5000}
    override: {skip-cert-verify: true, dialer-proxy: "百度直连", additional-suffix: " | 本地节点(YAML)"}

  # YAML/uri/base64 不可写在同一文件，uri/base64 不需要 proxies: 字段，直接书写即可
  # uri格式：vmess://eyJhZGQiOiIxMjcuMC4wLjEiLCJhaWQiOiIwIiwiYWxwbiI6IiIsImZwIjoiIiwiaG9zdCI6IiIsImlkIjoiMTIyMzQ1Njc4OSIsIm5ldCI6InRjcCIsInBhdGgiOiIiLCJwb3J0IjoiNDQzIiwicHMiOiJ2bWVzcyIsInNjeSI6ImF1dG8iLCJzbmkiOiIiLCJ0bHMiOiIiLCJ0eXBlIjoibm9uZSIsInYiOiIyIn0=
  本地节点(uri):
    type: file
    path: ./ProxyProviders/本地节点(uri).yaml
    health-check: {enable: true, url: https://www.gstatic.com/generate_204, interval: 86400, timeout: 5000}
    override: {skip-cert-verify: true, dialer-proxy: "百度直连", additional-suffix: " | 本地节点(uri)"}


# 混合端口是一个特殊的端口, 它同时支持 HTTP(S) 和 SOCKS5 协议. 您可以使用任何支持 HTTP 或 SOCKS 代理的程序连接到这个端口
mixed-port: 7890
# redirect 透明代理端口，仅能代理 TCP 流量
redir-port: 9797
# tproxy 透明代理端口，可代理 TCP 与 UDP 流量
tproxy-port: 9898
# 运行模式，rule 规则匹配 / global 全局代理(需要在GLOBAL策略组选择代理/策略) / direct 全局直连 此项拥有默认值，默认为规则模式
mode: rule
# 日志级别，silent：静默，不输出 / error：仅输出发生错误至无法使用的日志 / warning：输出发生错误但不影响运行的日志，以及 error 级别内容 / info：输出一般运行的内容，以及 error 和 warning 级别的日志 / debug：尽可能的输出运行中所有的信息
log-level: info
# 允许局域网，允许其他设备经过 Clash 的代理端口访问互联网
allow-lan: true
# 是否允许内核接受 IPv6 流量
ipv6: true
# 统一延迟，更换延迟计算方式，去除握手等额外延迟
unified-delay: true
# TCP连接并发，如果域名解析结果对应多个IP，并发所有IP，选择握手最快的 IP 进行连接
tcp-concurrent: true
# 外部控制 (API)，外部控制器，可以使用 RESTful API 来控制你的 Clash 内核
external-controller: 127.0.0.1:9090
# API 的访问密钥
secret: ""
# 外部用户界面，可以将静态网页资源（比如 Clash-dashboard) 运行在 Clash API, 路径为 API 地址/ui   可以为绝对路径，或者 Clash 工作目录的相对路径
external-ui: /ui
# 自定义外部用户界面下载地址
external-ui-url: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"
# GEO数据模式，更改 geoip 使用文件，mmdb 或者 dat，true 为 geoip.dat，此项有默认值 flase
geodata-mode: false
# 自动更新 GEO
geo-auto-update: false
# 更新间隔，单位小时
geo-update-interval: 24
# 自定 GEO 下载地址
geox-url:
  geoip: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"
  asn: "https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb"

# 在 Clash 官方中，profile 应为扩展配置，但在 Clash.meta, 仅作为缓存项使用
profile:
  # 储存 API 对策略组的选择，以供下次启动时使用。可选值为 true/false
  store-selected: true
  # 储存 fakeip 映射表（持久化fake-ip），域名再次发生连接时，使用原有映射地址。可选值为 true/false，
  store-fake-ip: false

#【Meta专属】域名嗅探器
sniffer:
  # 嗅探器开关
  enable: true
  sniff:
    # 需要嗅探的端口, 默认嗅探 80，全部端口为 0-65535
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  # 需要强制嗅探的域名（默认情况下只对 IP 进行嗅探）
  force-domain:
    - +.v2ex.com
  # 需要跳过嗅探的域名。主要解决部分站点 sni 字段非域名，导致嗅探结果异常的问题，如米家设备 Mijia Cloud
  skip-domain:
    - Mijia Cloud

tun:
  enable: true
  # tun 模式堆栈，如无使用问题，建议使用 system 栈，MacOS 用户推荐 gvisor 栈，可选：system/gvisor/lwip
  stack: system
  # dns 劫持，一般设置为 any:53 即可, 即劫持所有 53 端口的 udp 流量
  dns-hijack:
    - any:53
    - tcp://any:53
  # 自动设置全局路由，可以自动将全局流量路由进入 tun 网卡。可选：true/false
  auto-route: true
  # 自动选择流量出站接口，多出口网卡同时连接的设备建议手动指定出口网卡，可选：true/false
  auto-detect-interface: true
  # 黑名单(填UID)
  exclude-uid:
   # - 10114

dns:
  # 是否启用，如为 false，则使用系统 DNS 解析，可选值 true/false
  enable: true
  # dns 服务监听
  listen: 0.0.0.0:1053
  # 是否解析 IPV6, 如为 false, 则回应 AAAA 的空解析，可选值 true/false
  ipv6: true
  # Clash 的 dns 处理模式，可选值 fake-ip / redir-host
  enhanced-mode: fake-ip
  # fakeip 下的 IP 段设置，tun 网卡的默认 ip 也使用此值，格式为 ip/掩码（一般填 198.18.0.1/16 或 28.0.0.1/8）
  fake-ip-range: 198.18.0.1/16
  # fakeip 过滤，以下地址不会下发 fakeip 映射用于连接
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
  # 默认 dns, 用于解析 DNS 服务器 的域名。必须为 ip, 可为加密 dns
  default-nameserver:
    - 223.5.5.5
    - 223.6.6.6
  # 默认的域名解析服务器，如不配置 fallback/proxy-server-nameserver , 则所有域名都由 nameserver 解析
  nameserver:
    - "https://1.12.12.12/dns-query#国内代理"
    - "https://223.5.5.5/dns-query#国内代理"
  # 代理节点域名解析服务器，仅用于解析代理节点的域名
  proxy-server-nameserver:
    - "https://1.12.12.12/dns-query#百度直连"
  # 后备域名解析服务器，一般情况下使用境外 DNS, 保证结果可信，配置 fallback 后默认启用 fallback-filter，geoip-code 为 cn
  fallback:
    - "https://1.0.0.1/dns-query#国外代理"
    - "https://8.8.8.8/dns-query#国外代理"
  # 后备域名解析服务器筛选，满足条件的将使用 fallback 结果或只使用 fallback 解析
  fallback-filter:
    # 是否启用 fallback filter。可选值为 true/false
    geoip: true
    # 可选值为国家缩写，默认值为 CN。除了 geoip-code 配置的国家 IP, 其他的 IP 结果会被视为污染。geoip-code 配置的国家的结果会直接采用，否则将采用 fallback 结果
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
  # 指定域名查询的解析服务器，可使用 geosite, 优先于 nameserver/fallback 查询
  nameserver-policy:
    "geosite:cn,private":
      - "https://1.12.12.12/dns-query#国内代理"
      - "https://223.5.5.5/dns-query#国内代理"
# 想要走百度定向就删掉双引号里的彩信直连
p: &p {dialer-proxy: ""}


# 此处填节点，格式见 https://wiki.metacubex.one/config/proxies/vmess/
proxies:
  - {name: 直连, type: direct, udp: true}
  - {name: 广州移动, type: http, server: 183.240.98.84, port: 443, headers: {Host: gw.alicdn.com, X-T5-Auth: 234276684}, <<: *p} 
  - {name: 南京移动, type: http, server: 36.155.169.188, port: 443, headers: {Host: gw.alicdn.com, X-T5-Auth: 234276684}, <<: *p} 
  - {name: 南京电信, type: http, server: 180.101.50.249, port: 443, headers: {Host: gw.alicdn.com, X-T5-Auth: 234276684}, <<: *p}
  - {name: 苏州电信, type: http, server: 180.97.93.202, port: 443, headers: {Host: gw.alicdn.com, X-T5-Auth: 234276684}, <<: *p}
  - {name: 北京电信, type: http, server: 220.181.111.189, port: 443, headers: {Host: gw.alicdn.com, X-T5-Auth: 234276684}, <<: *p}
  - {name: 广州电信, type: http, server: 14.215.182.75, port: 443, headers: {Host: gw.alicdn.com, X-T5-Auth: 234276684}, <<: *p}
  - {name: 南京联通, type: http, server: 153.3.237.117, port: 443, headers: {Host: gw.alicdn.com, X-T5-Auth: 234276684}, <<: *p}
  - {name: 苏州联通, type: http, server: 157.0.148.53, port: 443, headers: {Host: gw.alicdn.com, X-T5-Auth: 234276684}, <<: *p}
  - {name: 保定联通, type: http, server: 110.242.70.68, port: 443, headers: {Host: gw.alicdn.com, X-T5-Auth: 234276684}, <<: *p}
  - {name: 广州联通, type: http, server: 163.177.17.189, port: 443, headers: {Host: gw.alicdn.com, X-T5-Auth: 234276684}, <<: *p}

# 代理(策略)组
proxy-groups:
  - name: 国外代理
    # select(手动选择) 或 url-test(自动测速)
    type: select
    # 排除关键词或正则表达式的节点，多个用|分隔
    exclude-filter: "江苏|镇江|浙江|南京|北京|上海|广东|苏州|杭州|福州|扬州|贵州|兰州|徐州|郑州|广西|河南|河北|重庆|南宁|宿迁|沈阳|四川|安徽|辽宁|济南|九江|长沙|昆明|武汉|陕西|西宁|芜湖|天津|南昌|成都|山西|太原|保定|湖南|SG|HK"
    # 根据节点类型排除(不支持正则表达式)，多个用|分隔。节点类型：HTTP SOCKS Shadowsocks ShadowsocksR VMess VLESS Trojan Hysteria Hysteria2 TUIC WireGuard
    exclude-type: ""
    proxies:
      - 国内节点
      
    use:
      - 本地节点(YAML)
      - 本地节点(uri)
      - 订阅1
      - 订阅2
      - 订阅3
      - 订阅4

  - name: 国内代理
    # select(手动选择) 或 url-test(自动测速)
    type: select
    # 筛选关键词或正则表达式的节点，多个用|分隔
    filter: "江苏|镇江|浙江|南京|北京|上海|广东|广州|苏州|杭州|福州|扬州|贵州|兰州|徐州|郑州|广西|河南|河北|重庆|南宁|宿迁|沈阳|四川|安徽|深圳|辽宁|济南|九江|长沙|昆明|武汉|陕西|西宁|芜湖|天津|南昌|成都|山西|太原|保定|湖南|香港|加拿大"
    proxies:
      - 百度直连
      
    use:
      - 本地节点(YAML)
      - 本地节点(uri)
      - 订阅1
      - 订阅2
      - 订阅3
      - 订阅4

  - name: Netflix
    # select(手动选择) 或 url-test(自动测速)
    type: select
    # 筛选关键词或正则表达式的节点，多个用|分隔
    filter: "江苏|镇江|浙江|南京|北京|上海|广东|广州|苏州|杭州|福州|扬州|贵州|兰州|徐州|郑州|广西|河南|河北|重庆|南宁|宿迁|沈阳|四川|安徽|深圳|辽宁|济南|九江|长沙|昆明|武汉|陕西|西宁|芜湖|天津|南昌|成都|山西|太原|保定|湖南|香港|加拿大|德国|3v1"
    proxies:
      - 国外代理
      
    use:
      - 本地节点(YAML)
      - 本地节点(uri)
      - 订阅1
      - 订阅2
      - 订阅3
      - 订阅4

  - name: 游戏UDP
    type: select
    filter: "镇江|浙江|南京|北京|上海|广东|广州|苏州|杭州|福州|扬州|贵州|兰州|徐州|郑州|广西|河南|河北|重庆|南宁|宿迁|沈阳|四川|安徽|深圳|辽宁|济南|九江|长沙|昆明|武汉|陕西|西宁|芜湖|天津|南昌|成都|山西|太原|保定|湖南"
    proxies:
      - 国内代理
      - 国外代理
     

  - name: 百度直连
    type: select
    proxies:
      - 广州移动
      - 南京联通
      - 苏州联通
      - 南京电信
      - 苏州电信
      - 北京电信
      - 广州电信
      
    url: 'https://www.gstatic.com/generate_204'
    interval: 86400
    lazy: true
    timeout: 5000

  - name: 广告拦截(anti-AD)
    type: select
    proxies:
      
      - REJECT

  - name: 广告拦截(秋风)
    type: select
    proxies:
      
      - REJECT

# 分流规则提供(订阅)组
rule-providers:
  gfw:
    type: http
    behavior: domain
    format: yaml
    path: ./RuleProviders/gfw.yaml
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    interval: 86400

  秋风广告规则:
    type: http
    behavior: domain
    format: yaml
    path: ./RuleProviders/AWAvenue-Ads-Rule-Clash.yaml
    url: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-hosts.txt"
    interval: 86400

  anti-AD:
    type: http
    behavior: domain
    format: yaml
    path: ./RuleProviders/Chatgpt.yaml
    url: "https://raw.githubusercontent.com/yilong001/ACL4SSR/main/Clash/config/Netflix/anti-AD.yaml"
    interval: 86400

# 分流规则
rules:
  - DOMAIN-KEYWORD,apiproxy-device-prod-nlb-,Netflix
  - DOMAIN-KEYWORD,dualstack.apiproxy-,Netflix
  - DOMAIN-KEYWORD,netflixdnstest,Netflix
  - DOMAIN,netflix.com.edgesuite.net,Netflix
  - DOMAIN-SUFFIX,fast.com,Netflix
  - DOMAIN-SUFFIX,netflix.com,Netflix
  - DOMAIN-SUFFIX,netflix.net,Netflix
  - DOMAIN-SUFFIX,netflixdnstest0.com,Netflix
  - DOMAIN-SUFFIX,netflixdnstest1.com,Netflix
  - DOMAIN-SUFFIX,netflixdnstest2.com,Netflix
  - DOMAIN-SUFFIX,netflixdnstest3.com,Netflix
  - DOMAIN-SUFFIX,netflixdnstest4.com,Netflix
  - DOMAIN-SUFFIX,netflixdnstest5.com,Netflix
  - DOMAIN-SUFFIX,netflixdnstest6.com,Netflix
  - DOMAIN-SUFFIX,netflixdnstest7.com,Netflix
  - DOMAIN-SUFFIX,netflixdnstest8.com,Netflix
  - DOMAIN-SUFFIX,netflixdnstest9.com,Netflix
  - DOMAIN-SUFFIX,nflxext.com,Netflix
  - DOMAIN-SUFFIX,nflximg.com,Netflix
  - DOMAIN-SUFFIX,nflximg.net,Netflix
  - DOMAIN-SUFFIX,nflxso.net,Netflix
  - DOMAIN-SUFFIX,nflxvideo.net,Netflix
  - IP-CIDR,8.41.4.0/24,Netflix,no-resolve
  - IP-CIDR,23.246.0.0/18,Netflix,no-resolve
  - IP-CIDR,37.77.184.0/21,Netflix,no-resolve
  - IP-CIDR,38.72.126.0/24,Netflix,no-resolve
  - IP-CIDR,45.57.0.0/17,Netflix,no-resolve
  - IP-CIDR,64.120.128.0/17,Netflix,no-resolve
  - IP-CIDR,66.197.128.0/17,Netflix,no-resolve
  - IP-CIDR,69.53.224.0/19,Netflix,no-resolve
  - IP-CIDR,103.87.204.0/22,Netflix,no-resolve
  - IP-CIDR,108.175.32.0/20,Netflix,no-resolve
  - IP-CIDR,185.2.220.0/22,Netflix,no-resolve
  - IP-CIDR,185.9.188.0/22,Netflix,no-resolve
  - IP-CIDR,192.173.64.0/18,Netflix,no-resolve
  - IP-CIDR,198.38.96.0/19,Netflix,no-resolve
  - IP-CIDR,198.45.48.0/20,Netflix,no-resolve
  - IP-CIDR,203.75.84.0/24,Netflix,no-resolve
  - IP-CIDR,207.45.72.0/22,Netflix,no-resolve
  - IP-CIDR,208.75.76.0/22,Netflix,no-resolve
  # 通过订阅规则进行广告拦截
  - RULE-SET,anti-AD,广告拦截(anti-AD)
  - RULE-SET,秋风广告规则,广告拦截(秋风)
  # 屏蔽索尼服务
  - DOMAIN-SUFFIX,playstation.net,REJECT
  # 通过域名关键字拦截 pcdn mcdn p2p tracker 的 udp 流量
  - AND,((NETWORK,UDP),(OR,(DOMAIN-KEYWORD,pcdn),(DOMAIN-KEYWORD,mcdn),(DOMAIN-KEYWORD,p2p),(DOMAIN-KEYWORD,tracker))),REJECT
  # 拦截 private ip 的 udp 流量
  - AND,((NETWORK,UDP),(GEOIP,PRIVATE)),REJECT
  # 通过包名放行 udp
  - AND,((NETWORK,UDP),(OR,(PROCESS-NAME,com.tencent.xriver),(PROCESS-NAME,com.tencent.tmgp.sgame),(PROCESS-NAME,com.tencent.mm),(PROCESS-NAME,com.tencent.tmgp.cf))),游戏UDP
  # 强制蓝奏云、123云盘、百度网盘上传、文叔叔下载走国外（百度直连专用）
  - AND,((OR,(DOMAIN-KEYWORD,oss),(DOMAIN-KEYWORD,lan),(DOMAIN-KEYWORD,wwentua),(DOMAIN-KEYWORD,123pan))),国外代理
  - AND,((OR,(DOMAIN-SUFFIX,update.pan.baidu.com),(DOMAIN-SUFFIX,down.wss.show))),国外代理
  # 前置域名代理
  - AND,((OR,(DOMAIN-SUFFIX,xn--ngstr-lra8j.com),(DOMAIN-SUFFIX,googleapis.cn),(DOMAIN-SUFFIX,dev))),国外代理
  # 国内域名规则
  - AND,((OR,(GEOSITE,category-games@cn),(GEOSITE,microsoft@cn),(GEOSITE,steam@cn),(GEOSITE,apple@cn,),(GEOSITE,bytedance),(GEOSITE,CN))),国内代理
  # 国外域名规则
  - GEOSITE,geolocation-!cn,国外代理
  # private ip 直连
  - GEOIP,PRIVATE,DIRECT,no-resolve
  # 国内 ip 规则
  - GEOIP,CN,国内代理
  # 兜底规则
  - MATCH,国外代理
